### ISSUE TITLE
 MacOs Catalina Installation Fix

### ISSUE THREAD

**Issue by Clovijan** [wictorChaves/CatalinaInstallVostro5470#1]
I'll put the link of the image that I used to install the catalina and the EFI folder that I'm using, you just need to install.

**Comment by Clovijan** [comment]
Links das pastas que utilizei:
Efi: https://drive.google.com/open?id=1TCLBwX0jknWNAGy0uCAdUjwVGK9nbkbB
Imagem Catalina:  link 1:   http://bit.ly/321lv9g
                                link 2:   http://bit.ly/37HtBoNo 
No Menu de boot do clover vc vai em configurações e e tem a opção de colocar comandos de inicialização coloque -no_compat_check aí ele não vai verificar a compatibilidade do hardware e ele inicia. foi assim que resolvi a maioria das coisas. A imagem tb só consegui resolver com essa aí. ela está desatualizada porém depois de instalar é só atualizar normalmente que dá certo.
Qualquer coisa: email: clovijan@gmail.com  
                            whatts: (79) 999152732 - Clovijan - Só falo português.

**Comment by wictorChaves** [comment]
Thanks [Clovijan](https://github.com/Clovijan), I already made changes to the project, now installation is possible.
